### ISSUE TITLE
How to generate an overlap of a self-made training set

### ISSUE THREAD

**Issue by joker-lb7** [aosheng1996/BUFFER#6]
Hi, aosheng
I am a novice, I want to make my own data set, I found that overlap is used in 3dmatch, how should I generate the overlap of the self-made training set.
thanks!

**Comment by Parskatt** [comment]
Also not an expert, but might be number of points that match divided by total number of points? Then you would have to set some threshold for how close points have to be to match.

**Comment by joker-lb7** [comment]
> Also not an expert, but might be number of points that match divided by total number of points? Then you would have to set some threshold for how close points have to be to match.

Thanks for your reply, I understand that in some point cloud registration methods, the overlap rate is just a record and does not affect the registration result, It is okay to give a random overlap ratio value. It is only used for logging. I wonder if I can do the same in BUFFER. I want to try it first.
